src/UTScheduler/urls.py
from django.contrib import admin
from django.urls import path, include
import polls.views

urlpatterns = [
    path('', polls.views.landing, name="landing"),
    path('poll/', include(('polls.urls', 'polls'), namespace="poll")),
    path('login/', polls.views.login, name="login"),
    path('validate/<username>', polls.views.validate_email, name="validate_email"),
    path('signup/', polls.views.signup, name="signup"),
    path('logout/', polls.views.logout, name="logout"),
    path('admin/', admin.site.urls),
]

src/polls/urls.py
from django.urls import path
import polls.views

urlpatterns = [
    path('', polls.views.my_polls, name="all"),
    path('new/', polls.views.new_poll, name="new"),
    path('<int:poll_id>', polls.views.handle_poll, name="show"),
    path('<int:poll_id>/choice', polls.views.add_choice, name="choice"),
    path('<int:poll_id>/choice/<choice_id>/del', polls.views.delete_choice, name="delete_choice"),
    path('<int:poll_id>/user', polls.views.add_user_to_poll, name="user"),
    path('<int:poll_id>/user/<user_name>/del', polls.views.delete_user_from_poll, name="delete_user"),
    path('<int:poll_id>/vote', polls.views.vote, name="vote"),
    path('<int:poll_id>/done', polls.views.end_poll, name="done"),
    path('<int:poll_id>/reopen', polls.views.begin_poll, name="reopen"),
    path('<int:poll_id>/choice/<int:choice_id>/comments', polls.views.get_comments, name="comments"),
    path('<int:poll_id>/choice/<int:choice_id>/comment', polls.views.add_comment, name="add_comment"),
    path('<int:poll_id>/choice/<int:choice_id>/comment/<int:comment_id>/replies', polls.views.get_replies, name="replies"),
    path('<int:poll_id>/choice/<int:choice_id>/comment/<int:comment_id>/reply', polls.views.reply_to_comment, name="reply_to_comment"),
]

src/polls/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=40, primary_key=True)
    email = models.EmailField()
    isRegistered = models.BooleanField(default=False)


class Poll(models.Model):
    question_text = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    audience = models.ManyToManyField(User)
    pub_date = models.DateTimeField(auto_now_add=True)
    close_date = models.DateTimeField(null=True)
    chosen_choice = models.ForeignKey('Choice', on_delete=models.CASCADE, null=True, related_name="chosen")
    POLL_T_TEXTUAL = 0
    POLL_T_TIMED = 1
    POLL_T_RECURRING = 2
    POLL_T = (
        (POLL_T_TEXTUAL, 'Textual'),
        (POLL_T_TIMED, 'Timed'),
        (POLL_T_RECURRING, 'Recurring'),
    )
    poll_type = models.IntegerField(choices=POLL_T, default=0)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

    def __str__(self):
        if self.poll.poll_type == Poll.POLL_T_TEXTUAL:
            return str(self.textchoice)
        elif self.poll.poll_type == Poll.POLL_T_TIMED:
            return str(self.timedchoice)
        elif self.poll.poll_type == Poll.POLL_T_RECURRING:
            return str(self.recurringchoice)
        else:
            raise NotImplementedError()


class TextChoice(Choice):
    content = models.CharField(max_length=200)

    def __str__(self):
        return self.content


class TimedChoice(Choice):
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)

    def overlaps(self, other):
        if other.__class__ == TimedChoice:
            if (self.start_date <= other.start_date <= self.end_date) or (
                self.start_date <= other.end_date <= self.end_date) or (
                other.start_date <= self.start_date <= other.end_date) or (
                other.start_date <= self.end_date <= other.end_date
            ):
                return True
            return False
        elif other.__class__ == RecurringChoice:
            if self.start_date.weekday() == other.weekday:
                if (self.start_date.time() <= other.start_time <= self.end_date.time()) or (
                    self.start_date.time() <= other.end_time <= self.end_date.time()) or (
                    other.start_time <= self.start_date.time() <= other.end_time) or (
                    other.start_time <= self.end_date.time() <= other.end_time
                ):
                        return True
            return False

    def __str__(self):
        return ('On: ' + str(self.start_date.strftime('%Y-%m-%d')) + ', ' + str(self.start_date.strftime('%H:%m'))
                + ' to ' + str(self.end_date.strftime('%H:%m')))


class RecurringChoice(Choice):
    WEEKDAYS = (
        (0, 'Monday'),
        (1, 'Tuesday'),
        (2, 'Wednesday'),
        (3, 'Thursday'),
        (4, 'Friday'),
        (5, 'Saturday'),
        (6, 'Sunday'),
    )
    weekday = models.IntegerField(choices=WEEKDAYS)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def overlaps(self, other):
        if other.__class__ == TimedChoice:
            if self.weekday == other.start_date.weekday():
                if (self.start_time <= other.start_date.time() <= self.end_time) or (
                    self.start_time <= other.end_date.time() <= self.end_time) or (
                    other.start_date.time() <= self.start_time <= other.end_date.time()) or (
                    other.start_date.time() <= self.end_time <= other.end_date.time()
                ):
                    return True
            return False
        elif other.__class__ == RecurringChoice:
            if self.weekday == other.weekday:
                if (self.start_time <= other.start_time <= self.end_time) or (
                    self.start_time <= other.end_time <= self.end_time) or (
                    other.start_time <= self.start_time <= other.end_time) or (
                    other.start_time <= self.end_time <= other.end_time
                ):
                        return True
            return False

    def __str__(self):
        return ('Every ' + str(self.WEEKDAYS[self.weekday][1]) + ', ' + str(self.start_time.strftime('%H:%M'))
                + ' to ' + str(self.end_time.strftime('%H:%M')))


class Vote(models.Model):
    VOTE_T = (
        (1, 'Yes'),
        (0, 'Maybe'),
        (-1, 'No'),
    )
    voter = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    vote = models.IntegerField(choices=VOTE_T)

    class Meta:
        unique_together = (("voter", "choice"),)


class Comment(models.Model):
    choice = models.ForeignKey('Choice', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    comment_text = models.CharField(max_length=400)

src/polls/views.py
from django.shortcuts import render, Http404, redirect, reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db.utils import IntegrityError
from django.utils.timezone import now
from django.contrib import messages
from datetime import datetime

from .models import User, Poll, Choice, Vote, TextChoice, TimedChoice, RecurringChoice, Comment
from .mail.mail import Mail
from .mail.notifier import Notifier


# todo: should refactor or combine with involvement
def needs_involvement_or_ownership(func):
    def involvement_or_ownership_checked_func(req, poll_id, *args, **kwargs):
        try:
            poll = Poll.objects.get(id=poll_id)
        except ObjectDoesNotExist:
            raise Http404
        if poll and (poll.audience.filter(name=req.puser.name).exists() or poll.owner == req.puser):
            return func(req, poll, *args, **kwargs)
        else:
            raise Http404

    return involvement_or_ownership_checked_func


def needs_involvement(func):
    def involvement_checked_func(req, poll_id, *args, **kwargs):
        try:
            poll = Poll.objects.get(id=poll_id)
        except ObjectDoesNotExist:
            raise Http404
        if poll and poll.audience.filter(name=req.puser.name).exists():
            return func(req, poll, *args, **kwargs)
        else:
            raise Http404

    return involvement_checked_func


def needs_ownership(func):
    def ownership_checked_func(req, poll_id, *args, **kwargs):
        try:
            poll = Poll.objects.get(id=poll_id)
        except ObjectDoesNotExist:
            raise Http404
        if poll and poll.owner == req.puser:
            return func(req, poll, *args, **kwargs)
        else:
            raise Http404

    return ownership_checked_func


def is_poll_closed(poll):
    return poll.close_date and poll.close_date < now()


def only_open_polls(func):
    def opennes_checkec_function(req, poll, *args, **kwargs):
        if not is_poll_closed:
            raise Http404
        else:
            return func(req, poll, *args, **kwargs)

    return opennes_checkec_function


def landing(req):
    return redirect(reverse('poll:all'))


def my_polls(req):
    owned_polls = Poll.objects.filter(owner=req.puser)
    involved_polls = Poll.objects.filter(audience=req.puser)
    return render(req, "polls/my_polls.html", {"owned_polls": owned_polls, "involved_polls": involved_polls})


def login(req):
    if req.method == 'GET':
        return render(req, "login.html")
    elif req.method == 'POST':
        try:
            user = User.objects.get(name=req.POST['username'], isRegistered=True)
            req.session['username'] = user.name
            return redirect(reverse('landing'))
        except (ObjectDoesNotExist, ValueError, KeyError):
            messages.add_message(req, messages.ERROR, "Wrong authentication data!")
            return render(req, "login.html", status=401)
    else:
        raise Http404


def signup(req):
    if req.method == 'GET':
        return render(req, "signup.html")
    elif req.method == 'POST':
        try:
            User.objects.create(name=req.POST['username'], email=req.POST['email'], isRegistered=False)
            Notifier(Mail()).reg_user(
                User.objects.get(name=req.POST['username']),
                req.build_absolute_uri(reverse('validate_email', kwargs={
                    'username': User.objects.get(name=req.POST['username']).name
                }))
            )
            messages.add_message(req, messages.SUCCESS, "User created successfully! Please validate your email")
            return redirect(reverse('login'))
        except (IntegrityError, ValueError, KeyError):
            messages.add_message(req, messages.ERROR, "Duplicate username!")
            return redirect(reverse('signup'))
    else:
        raise Http404


def validate_email(req, username):
    try:
        user = User.objects.get(name=username)
    except (ObjectDoesNotExist):
        raise Http404
    user.isRegistered = True
    user.save()
    messages.add_message(req, messages.SUCCESS, "User validate successfully.")
    return redirect(reverse('login'))


def logout(req):
    req.session['username'] = None
    return redirect(reverse('landing'))


def new_poll(req):
    try:
        if req.method == 'GET':
            return render(req, "polls/new_poll.html", {'types': Poll.POLL_T})
        elif req.method == 'POST':
            poll = Poll.objects.create(question_text=req.POST['question'], owner=req.puser, poll_type=req.POST['type'])
            messages.add_message(req, messages.SUCCESS, "Poll created successfully!")
            return redirect(reverse('poll:show', kwargs={'poll_id': poll.id}))
        else:
            raise Http404
    except ObjectDoesNotExist:
        raise Http404


@needs_ownership
def handle_poll_for_owner(req, poll):
    return render(req, "polls/poll_details.html", {
        "poll": poll,
        "choices": [{"choice": choice, "votes": [
            {"text": opt[1], "num": Vote.objects.filter(choice=choice, vote=opt[0]).count()}
            for opt in Vote.VOTE_T
        ]} for choice in Choice.objects.filter(poll=poll)],
        "involved_users": User.objects.filter(poll=poll, isRegistered=True),
        "users": User.objects.exclude(poll=poll).exclude(owner=poll).filter(isRegistered=True),
        "closed": is_poll_closed(poll),
        "chosen": poll.chosen_choice if is_poll_closed(poll) else "",
        "weekdays": RecurringChoice.WEEKDAYS
    })


@needs_involvement
def handle_poll_for_audience(req, poll):
    def get_first_vote(l):
        return l[0].get_vote_display() if len(l) else None

    return render(req, "polls/poll_vote.html", {
        "poll": poll,
        "choices": [{'choice': choice, 'vote': get_first_vote(Vote.objects.filter(voter=req.puser, choice=choice))}
                    for choice in Choice.objects.filter(poll=poll)],
        "possible_votes": [vote[1] for vote in Vote.VOTE_T],
        "closed": is_poll_closed(poll),
        "chosen": poll.chosen_choice.content if is_poll_closed(poll) else ""
    })


def handle_poll(req, poll_id):
    try:
        return handle_poll_for_owner(req, poll_id)
    except Http404:
        return handle_poll_for_audience(req, poll_id)


@needs_ownership
@only_open_polls
def add_choice(req, poll):
    if req.method == 'POST':
        status = messages.SUCCESS
        status_msg = "Choice created successfully!"
        if poll.poll_type == Poll.POLL_T_TEXTUAL:
            TextChoice.objects.create(poll=poll, content=req.POST['text'])
        elif poll.poll_type == Poll.POLL_T_TIMED:
            try:
                start_datetime = datetime.strptime(req.POST['start-date'] + ' ' + req.POST['start-time'],
                                                   '%Y-%m-%d %H:%M')
                end_datetime = datetime.strptime(req.POST['start-date'] + ' ' + req.POST['end-time'],
                                                 '%Y-%m-%d %H:%M')
                if start_datetime >= end_datetime:
                    raise Exception
                TimedChoice.objects.create(poll=poll, start_date=start_datetime, end_date=end_datetime)
            except Exception:
                status = messages.ERROR
                status_msg = "Wrong datetime format!"
        elif poll.poll_type == Poll.POLL_T_RECURRING:
            try:
                start_time = datetime.strptime(req.POST['start-time'], '%H:%M').time()
                end_time = datetime.strptime(req.POST['end-time'], '%H:%M').time()
                weekday = int(req.POST['weekday'])
                if start_time >= end_time or weekday < 0 or weekday > 6:
                    raise Exception
                RecurringChoice.objects.create(poll=poll, weekday=weekday, start_time=start_time, end_time=end_time)
            except Exception:
                status = messages.ERROR
                status_msg = "Wrong time format!"

        messages.add_message(req, status, status_msg)
        return redirect(reverse('poll:show', kwargs={'poll_id': poll.id}))
    else:
        raise Http404


@needs_ownership
@only_open_polls
def add_user_to_poll(req, poll):
    if req.method == 'POST':
        try:
            this_audience = User.objects.get(name=req.POST['username'], isRegistered=True)
        except (ObjectDoesNotExist, ValueError, KeyError):
            raise Http404
        poll.audience.add(this_audience)
        Notifier(Mail()).notify_participate(
            req.puser,
            this_audience,
            req.build_absolute_uri(reverse('poll:show', kwargs={'poll_id': poll.id}))
        )
        messages.add_message(req, messages.SUCCESS, "User added successfully!")
        return redirect(reverse('poll:show', kwargs={'poll_id': poll.id}))
    else:
        raise Http404


@needs_involvement
@only_open_polls
def vote(req, poll):
    choice_prefix = 'vote_'
    if req.method == 'POST':
        status = messages.SUCCESS
        status_msg = "Voted successfully!"
        for idx, key in enumerate(req.POST):
            if key.startswith(choice_prefix):
                try:
                    choice = Choice.objects.get(id=key[len(choice_prefix):])
                except (ObjectDoesNotExist, ValueError, KeyError):
                    raise Http404
                if choice.poll != poll:
                    raise Http404
                Vote.objects.update_or_create(
                    voter=req.puser,
                    choice=choice,
                    defaults={'vote': {key: value for (value, key) in Vote.VOTE_T}[req.POST[key]]},
                )
                if {key: value for (value, key) in Vote.VOTE_T}[req.POST[key]] == 1:
                    other_votes = Vote.objects.filter(voter=req.puser, vote=1)
                    for other_vote in other_votes:
                        choice_overlap = False
                        if other_vote.choice == choice:
                            continue

src/templates/polls/choice_comments.html
{% extends '../trunk.html' %}
{% block content %}
{% if closed %}
<h4>Poll Closed With:</h4>
<h6>{{chosen}}</h6>
{% else %}
<h3>comments: {{choice}}</h3>
<ul>
    {% for comment in comments %}
        <li class="form-group">
            <div class="form-check-inline">
                {{comment.comment_text}}
            </div>
        </li>
    {% endfor %}
    </ul>

    <form action="{% url 'poll:add_comment' poll.id choice.id%}" method="POST">
        <input type="text" class="form-control mb-2 mr-sm-2 mb-2" name="comment_text" required placeholder="Hi there!">
        <button type="submit" class="btn btn-success btn-block">Add Comment</button>
    </form>

{% endif %}
{% endblock %}

src/templates/polls/comment_replies.html
{% extends '../trunk.html' %}
{% block content %}
{% if closed %}
<h4>Poll Closed With:</h4>
<h6>{{chosen}}</h6>
{% else %}
<h2>comments: {{choice}}</h2>
<h4>replies: {{comment.comment_text}}</h4>
<ul>
    {% for comment in replies %}
        <li class="form-group">
            <a href="{% url 'poll:replies' poll.id choice.id comment.id%}" class="btn btn-primary btn-sm mb-2"><span class="far fa-comment"></span></a>
            <div class="form-check-inline">
                {{comment.comment_text}}
            </div>
        </li>
    {% endfor %}
    </ul>

    <form action="{% url 'poll:reply_to_comment' poll.id choice.id comment.id %}" method="POST">
        <input type="text" class="form-control mb-2 mr-sm-2 mb-2" name="comment_text" required placeholder="Hi there!">
        <button type="submit" class="btn btn-success btn-block">Add Reply</button>
    </form>

{% endif %}
{% endblock %}

src/templates/polls/my_polls.html
{% extends '../trunk.html' %}
{% block content %}
<h2>Owned Polls</h2>
<ul>
{% for poll in owned_polls %}
    <li><a href="{% url 'poll:show' poll.id %}">{{poll.question_text}}</a></li>
{% endfor %}
</ul>
<a href="{% url 'poll:new' %}" class="btn btn-success mb-2"> New Poll</a>

<h2>Involved Polls</h2>
<ul>
{% for poll in involved_polls %}
    <li><a href="{% url 'poll:show' poll.id %}">{{poll.question_text}}</a></li>
{% endfor %}
</ul>
{% endblock %}

src/templates/polls/new_poll.html
{% extends '../trunk.html' %}
{% block title %} :: New Poll{% endblock %}
{% block content %}
<h1><span class="fas fa-poll"></span> New Poll</h1>
<form action="{% url 'poll:new' %}" method="POST">
    <div class="form-group">
        <label for="question">Poll:</label>
        <input type="text" class="form-control" name="question" required placeholder="To be or not to be?">
    </div>
    <label for="type" class="mr-sm-2">Poll Type:</label>
    <select name="type" required class="custom-select form-control mb-2 mr-sm-2 mb-2">
        {% for type in types %}
        <option value="{{type.0}}">{{type.1}}</option>
        {% endfor %}
    </select>
    <button type="submit" class="btn btn-success btn-block">Add Poll</button>
</form> 
{% endblock %}

src/templates/polls/poll_details.html
{% extends '../trunk.html' %}
{% block content %}
<h3>{{poll.question_text}}</h3>
<h4>Choices</h4>
<ul>
{% for choice in choices %}
<li>
    <span>{{choice.choice}}</span>
    {% if not closed %}
    &nbsp;
    <a href="{% url 'poll:delete_choice' poll.id choice.choice.id %}" class="btn btn-danger btn-sm mb-2"><span class="far fa-minus-square"></span></a>
    <a href="{% url 'poll:comments' poll.id choice.choice.id %}" class="btn btn-primary btn-sm mb-2"><span class="far fa-comment"></span></a>
    {% endif %}
    <dl>
        {% for vote in choice.votes %}
        <dt>{{vote.text}}</dt>
        <dd>{{vote.num}}</dd>
        {% endfor %}
    </dl>
</li>
{% endfor %}
</ul>
{% if not closed %}
<form action="{% url 'poll:choice' poll.id %}" method="POST" class="form-inline">
    {% if poll.poll_type == poll.POLL_T_TEXTUAL %}
    <label for="text" class="mr-sm-2">Choice:</label>
    <input type="text" class="form-control mb-2 mr-sm-2 mb-2" name="text" placeholder="Hamlet" required id="text">
    {% elif poll.poll_type == poll.POLL_T_TIMED %}
    <label for="start-date" class="mr-sm-2">On:</label>
    <input type="date" class="form-control mb-2 mr-sm-2 mb-2" name="start-date" required id="start-date">
    <label for="start-date" class="mr-sm-2">Start time:</label>
    <input type="time" class="form-control mb-2 mr-sm-2 mb-2" name="start-time" required id="start-time">
    <label for="start-date" class="mr-sm-2">End time:</label>
    <input type="time" class="form-control mb-2 mr-sm-2 mb-2" name="end-time" required id="end-time">
    {% elif poll.poll_type == poll.POLL_T_RECURRING %}
    <select name="weekday" required class="custom-select form-control mb-2 mr-sm-2 mb-2">
        <option disabled selected hidden>Funday</option>
        {% for weekday in weekdays %}
        <option value="{{weekday.0}}">{{weekday.1}}</option>
        {% endfor %}
    </select>
    <label for="start-date" class="mr-sm-2">Start:</label>
    <input type="time" class="form-control mb-2 mr-sm-2 mb-2" name="start-time" required id="start-time">
    <label for="end-date" class="mr-sm-2">End:</label>
    <input type="time" class="form-control mb-2 mr-sm-2 mb-2" name="end-time" required id="end-time">
    {% endif %}
    <button type="submit" class="btn btn-success mb-2"><span class="far fa-plus-square"></span></button>
</form>
{% endif %}
<h4>Involved People</h4>
<ul>
    {% for user in involved_users %}
    <li>
        <span>{{user.name}}</span>
        {% if not closed %}
        &nbsp;
        <a href="{% url 'poll:delete_user' poll.id user.name %}" class="btn btn-danger btn-sm mb-2"><span class="fas fa-user-minus"></span></a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% if not closed %}
<form action="{% url 'poll:user' poll.id %}" method="POST" class="form-inline">
    <label for="username" class="mr-sm-2">User:</label>
    <select name="username" required class="custom-select form-control mb-2 mr-sm-2 mb-2">
        <option disabled selected hidden>Hamlet</option>
        {% for user in users %}
        <option value="{{user.name}}">{{user.name}}</option>
        {% endfor %}
    </select>
    <button type="submit" class="btn btn-success mb-2"><span class="fas fa-user-plus"></span></button>
</form>
{% endif %}
{% if not closed %}
<h4>Close Poll</h4>
<form action="{% url 'poll:done' poll.id %}" method="POST" class="form-inline">
    <select name="choice" required class="custom-select form-control mb-2 mr-sm-2 mb-2">
            <option disabled selected hidden>To be?</option>
            {% for choice in choices %}
            <option value="{{choice.choice.id}}">{{choice.choice}}</option>
            {% endfor %}
        </select>
    <button type="submit" class="btn btn-warning mb-2"> Close Poll</button>
</form>
{% else %}
<p>Poll closed with: {{chosen}}</p>
<form action="{% url 'poll:reopen' poll.id %}" method="POST" class="form-inline">
    <button type="submit" class="btn btn-warning mb-2"> Reopen Poll</button>
</form>
{% endif %}
{% endblock %}

src/templates/polls/poll_vote.html
{% extends '../trunk.html' %}
{% block content %}
{% if closed %}
<h4>Poll Closed With:</h4>
<h6>{{chosen}}</h6>
{% else %}
<h3>{{poll.question_text}}</h3>
<form action="{% url 'poll:vote' poll.id %}" method="POST">
    <ul>
        {% for choice in choices %}
        <li class="form-group">
            <a href="{% url 'poll:comments' poll.id choice.choice.id %}" class="btn btn-primary btn-sm mb-2"><span class="far fa-comment"></span></a>
            <div class="form-check-inline">
                {{choice.choice}}
            </div>
            {% for vote in possible_votes %}
            <div class="form-check-inline">
                <label class="form-check-label">
                <input type="radio" class="form-check-input" name="vote_{{choice.choice.id}}" value="{{vote}}" {% if choice.vote == vote %}checked{% endif %}>{{vote}}
              </label>
            </div>
            {% endfor %}
        </li>
        {% endfor %}
    </ul>
    <button type="submit" class="btn btn-success">Vote</button>
</form>
{% endif %}
{% endblock %}